name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Bright Ran'

inputs:
  expire-in:
    required: true
    description: 'Human readable expire duration'
  token:
    required: true
    description: 'Github auth token'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
